### ISSUE TITLE
[Question] best strategy for Continuous delivery pipeline

### ISSUE THREAD

**Issue by dtcMLOps** [mikepenz/release-changelog-builder-action#1036]
Hi @mikepenz,

Hope you find very well.

I would like to ask you for your advice regarding a CD pipeline that I am implementing using the changelog generator as a job. Basically, my CD pipelines looks as follows:

![Screenshot from 2023-03-01 06-59-50](https://user-images.githubusercontent.com/115469901/222133502-5f7793bb-bffc-4854-9430-9736c50e023b.png)

I am calculating a semantic version, then compile a package, and then creating a tag based on the new sem version. The changelog generator uses those tags to extract the PRs and then I create a release.

The good thing with this is that I have a section called `Changes` with this format (using both tags)

![Screenshot from 2023-03-01 07-04-25](https://user-images.githubusercontent.com/115469901/222134419-b1b0e3b6-847a-4d1c-95a4-01b81e8ef31d.png)

The problem with that approach is that if something goes wrong in the changelog generation (maybe not merged PRs are found or something like that) and then I re-run the pipeline I will get an error because a Tag was already created and I will have to delete or overwrite that tag.

My understanding of good practices is that the "tag" should be created in the latest job with `create release` instead before the changelog generation process. So, my new approach was to remove the create tag before changelog generation and leave that part to the latest job in the `create release`.

![Screenshot from 2023-03-01 07-12-07](https://user-images.githubusercontent.com/115469901/222136027-08dc351f-0bf2-4902-b646-a9b31162226a.png)

To make this work, I am using `${{ github.ref }}` in the `toTag` parameter in the changelog and not a tag. And this works, but now the Changes section looks as follows:

![Screenshot from 2023-03-01 07-07-21](https://user-images.githubusercontent.com/115469901/222135065-18e556f5-fba0-4791-a740-622546e75d0f.png)

My question after all this context is: How can I update the changelog "Changes" section to use a tag that is being created after the release process in the changelog markdown description? I know I can modify manually the release content and overwrite the `${{RELEASE_DIFF}}` with the latest tag. But, I was wondering if we can have a way to tell the changelog to use this fromTag and toTag to the `${{RELEASE_DIFF}}` even if the `toTag` does not exist yet. Or, what do you think about this?

The goal of this is to have the second approach with the "Changes" section using the previous and the new sem version tag

**Comment by mikepenz** [comment]
@dtcMLOps thank you very much for this very very detailed description, and sorry for the late answer. 

From the actions perspective the automated `RELEASE_DIFF` can only use the `fromTag` to `toTag` values, as it wouldn't know about any other context you describe. And adding something just to modify this placeholder would introduce quite some overhead. 

That being said though. 

I assume you use the ${{RELEASE_DIFF}} as part of your `TEMPLATE`. Then there is the question if you provide the `json` configuration via file or via the `yaml` build. 

Anyways. Ultimately the `RELEASE_DIFF` template is very simple as it only builds the well known link. 

So what you can do instead:

```https://github.com/${options.owner}/${options.repo}/compare/${options.fromTag.name}...${options.toTag.name}```

You can add this to the template (if it is used via the yaml)

```
https://github.com/#{{OWNER}}/#{{REPO}}/compare/#{{FROM_TAG}}...${{CI_VARIABLE}}
```
Providing the `to_tag` via the CI environment

(`#{{}}` because in the CI yml `${{}}` is protected by GitHub) 

If it's a file, you could replace the last part in the `json` config file, prior to running the action. 

And third, as you noted yourself, you can "just" add that part to the changelog after it was built, or do a string replace of the last section to reflect your expected `to` value.

**Comment by mikepenz** [comment]
Please report back if there are follow up questions. Closing as done.
