### ISSUE TITLE
deactivate categories

### ISSUE THREAD

**Issue by KonradHoeffner** [mikepenz/release-changelog-builder-action#1267]
I don't use any categories for my commits, so everything is under the "uncategorized" headline. Is it possible to get rid of this headline especially when there are no other categories?

**Comment by mikepenz** [comment]
The default template for v4 uses: 
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L76-L93

and:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L73


You can probably achieve what you are looking for by adjusting the `template` to only be `#{{UNCATEGORIZED}}` instead of `#{{CHANGELOG}}`

**Comment by mikepenz** [comment]
Please find all configuration options in the README: https://github.com/mikepenz/release-changelog-builder-action?tab=readme-ov-file#template-placeholders
