### ISSUE TITLE
Cannot read property 'merged_at' of undefined

### ISSUE THREAD

**Issue by ngosang** [mikepenz/release-changelog-builder-action#127]
I can't execute this action. I think it's caused because my fork doesn't have the original PRs

![image](https://user-images.githubusercontent.com/10577978/102703371-305a6b80-426e-11eb-8719-5ec912388fd2.png)

**Comment by mikepenz** [comment]
Is the repo this happened on open source? If that's the case I'd love to debug it. 

Otherwise would it be possible to create a sample repo which would allow me to reproduce this issue?

**Comment by ngosang** [comment]
Yes, the repository is opensource.
- Fork this repository => https://github.com/FlareSolverr/FlareSolverr
- Your action is configured in this workflow => https://github.com/FlareSolverr/FlareSolverr/blob/master/.github/workflows/release.yml
- Just push a new tag to your repository. You should be able to reproduce it.

**Comment by mikepenz** [comment]
Thank you so much. I'll look at it tomorrow.

**Comment by mikepenz** [comment]
@ngosang so I have had a look and it looks the problem is due to the try of generating the changelog for a repo on which there is no PRs.

I'll fix the related undefined exception, but the action builds changelogs based on PRs so it won't be able to build the changelog on a fork for a different repo. 

What you can do is to specify a different repo to use for building the changelog for, but it defeats the goal. 

May you be able to describe a bit more on the process you envision? 

thank you so much

**Comment by ngosang** [comment]
> May you be able to describe a bit more on the process you envision?

I use my fork to test GitHub Actions before executing them in the public Project. I use this action to publish releases and I don't want to publish "test releases" until it works as expected. This project is fine as it's, thank you!

Do you now a similar GitHub Action to build the changelog based on commits instead of PRs?

**Comment by mikepenz** [comment]
I see. 

There are a few other github actions which would be based on commits instead of pull requests, but you'd have to research your own for these :)
