### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by GoulvenF** [mikepenz/release-changelog-builder-action#1293]
Thanks for your great action ;)

Would it make sense to allow  the use of custom variables (defined from env, mainly) to the template ? 

eg. 

number of lines : #{{LINE_COUNT}}

Would be usefull in my case !

Best regards

**Comment by mikepenz** [comment]
Thank you very much. 

I believe this is already supported. Configure the json within your workflow file directly, allowing you to use any GitHub action placeholder variable in place too:

https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L142-L155


(otherwise you can also do by writhing the config file to json via GitHub actions and repalce some items with your respective values)

**Comment by mikepenz** [comment]
Please let me know if this answered your question. Closing for now as I believe this is already possible with the current APIs

**Comment by GoulvenF** [comment]
Yes, sorry for the late answer ! I did not dig into it but your informations trends to flag it as already possible !

Thanks
