### ISSUE TITLE
Usage info for parallel releases support

### ISSUE THREAD

**Issue by jorgnava** [mikepenz/release-changelog-builder-action#288]
First of all, congrats for this great repo.

I´ve read on the docs that parallel releases are supported but I´m not able to configure it correctly so maybe I got a different concept of it.

I´ll try to explain what I want to achieve. I got a master/main branch where tags get pushed to, additionally at feature branches there are also tags to release partial features. All branches have Pull Requests associated, so an example would be:

```
master (0.0.1, 0.0.2...)
  featureA (0.0.1-featureA.1, 0.0.1-featureA.2 ...)
     ticket-1
     ticket-2
  featureB (0.0.1-featureB.1, 0.0.1-featureB.2 ...)
     ticket-3
     ticket-4
```

Is this structure supported?

If it is not, could I get at least the changelog for the master tags? (0.0.1, 0.0.2...) Every pull requests gets not categorized, I tried to replicate some of your projects with this actions with no result.

[Here is a test repository](https://github.com/jorgnava/changelog-test)

**Comment by mikepenz** [comment]
@jorgnava in principle your approach should be possible. 

The action will use the commits between 2 tags and identify the associated PRs to those. 

Thanks for providing the test repo. Will have a look into what it does there in the upcoming days. 

One thing I see in the test repo is, that none of the PRs got a `label` associated. Labels are a core part for this action as they are used to move PRs in the respective categories, otherwise PRs will simply be non categorized instead

**Comment by jorgnava** [comment]
@mikepenz Oh I see, I thought `label` extracts also for title by default.

We use conventional commits on PRs so with a proper label_extractor I guess it will work as this PR states #208 

With all this new info and your guess of this approach to be possible, I think the best is to close the issue and try on my own. I´ll reopen if something comes up and only when the test repo is updated.
