### ISSUE TITLE
Add Jira ticket URL to commit messages

### ISSUE THREAD

**Issue by 4szt4l** [mikepenz/release-changelog-builder-action#389]
Is there a way to have custom URL using regex from commit messages?
When creating release notes from commits, I would like those commits to point to the related Jira issue. E.g. this commit message: `feat/MYPROJ-15-add-unit-tests` would point to https://my.jira/MYPROJ-15
I tried to use a custom label to paste it after a URL but I couldn't figure it out how.

**Comment by mikepenz** [comment]
What I use in some projects is to have the JIRA ticket number as part of the title of a PR. So I use the `transforms` to extract the JIRA ticket number from the `title`, knowing the `pr_template` format. 


```json
{
  "template": "${{CHANGELOG}}",
  "pr_template": "- ${{TITLE}}\n   - PR: #${{NUMBER}}",
  "empty_template": "- no changes",
  "transformers": [
    {
      "pattern": "[\\-\\*] (\\[(X.+?)\\])(\\[(X.+?)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
      "target": "- $6\n  - FIX https://my.jira.com/browse/$2\n  - FIX https://my.jira.com/browse/$4 | $8"
    },
    {
      "pattern": "[-\\*] (\\[(X.+?)\\])(\\[(.+?)\\])?( )?(.+?)\n(.+?[\\-\\*] )(.+)",
      "target": "- $6\n  - FIX https://my.jira.com/browse/$2 | $8"
    },
    {
      "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
      "target": "- $4\n  - $6"
    }
  ]
}
```

So I expect titles to be in the format of:

```
[XYZ-123] My PR is awesome and fixes things
```

or alternative maybe as

```
[SKIP] This is a PR to be skipped
```

**Comment by dalezak** [comment]
@mikepenz curious how to handle the following PR title formats:

- GSP-2607 Create GraphQL endpoint for Vetting
- [GSP-2607] Create GraphQL endpoint for Vetting
- Create GraphQL endpoint for Vetting

Would the following transformers convert correctly?

```
"transformers": [
    {
      "pattern": "[GSP-\\d{1,}] \\[(GSP-\\d{1,})\\] ([a-zA-Z0-9 _\\s]*)",
      "target": "$2 [$1](https://my-app.atlassian.net/browse/$1)"
    },
    {
    "pattern": "GSP-\\d{1,} (GSP-\\d{1,}) ([a-zA-Z0-9 _\\s]*)",
    "target": "$2 [$1](https://my-app.atlassian.net/browse/$1)"
    }
  ],
```

**Comment by dalezak** [comment]
@mikepenz I can confirm the above transformers works exactly as expected 🥳

**Comment by perspilling** [comment]
I would like to match end-of-line, but $ doesn't seem to work?

**Comment by perspilling** [comment]
Here is a screenshot from tubular.com 
![Screenshot 2022-10-19 at 16 05 17](https://user-images.githubusercontent.com/151178/196714047-8d410b2e-2193-4330-9d3d-89aa496a17cd.png)

**Comment by mikepenz** [comment]
@perspilling pushed a test-case to a new branch: https://github.com/mikepenz/release-changelog-builder-action/commits/test/389_2

It's easiest and fastest to debug such situations locally. 

Given the sample test-case the simpler regex seems to properly extract the value

You can see instructions for local testing here: https://github.com/mikepenz/release-changelog-builder-action#local-testing-
(standard npm setup is needed - node 16 and to run `npm install`) 

Only to make sure I mentioned it. The `transformer` is applied on the filled template, so maybe there is a difference? 

----

Since this ticket was created there was a new function introduced (currently still experimental) - which allows to define `custom placeholders` -> you extract a value, and that value can be used within the template afterwards. 

This may be a more convenient option today: https://github.com/mikepenz/release-changelog-builder-action#experimental-

**Comment by mikepenz** [comment]
Pushed a second commit using the placeholder feature.
- https://github.com/mikepenz/release-changelog-builder-action/commit/aacfbea1f18e77e2934cc7d5cf4bf2f44e2d1369

The javascript code uses the regex as part of a `replace` condition - https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/transform.ts#L338

**Comment by perspilling** [comment]
Thx for your help. The problem is that both the 
CRIC-1234<EOL> and 
CRIC-1234: <title> 
might exist. I can match both with a simple "(CRIC-\\d{4})" pattern, but that doesn't look so nice in the latter case. The version without a title is not common, so I guess I just leave it like it is, and notify the team that that we should standardise on a certain style for how to write the PR title :-)

**Comment by perspilling** [comment]
I works locally btw

**Comment by mikepenz** [comment]
@perspilling if you configure the action via the json in the `yml` file itself, the github templates should be inserted. 

In that case please be aware that the template for the action is `#{{}}` instead: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/.github/workflows/ci.yml#L47-L73
