### ISSUE TITLE
Failed to retrieve - Invalid tag? - Because of: HttpError: Not Found

### ISSUE THREAD

**Issue by risoms** [mikepenz/release-changelog-builder-action#427]
I've been running into the same issue where I'm seeing a Failed to retrieve message. I'm wondering what I might be doing to cause this? Just in case it's relevant, the versioning in my repo does not use semver unfortunately. 

![image](https://user-images.githubusercontent.com/10383917/128580994-8f61645c-194d-4fc2-b6c9-3397f9d3f35c.png)

**Comment by mikepenz** [comment]
The exception is thrown here: https://github.com/mikepenz/release-changelog-builder-action/blob/f2fcbb1f9ba84c179463cf065adf7709b7cad6f5/src/releaseNotes.ts#L62

Due to the `HttpError: Not Found` it seems that the request could not be done here:
https://github.com/mikepenz/release-changelog-builder-action/blob/f2fcbb1f9ba84c179463cf065adf7709b7cad6f5/src/commits.ts#L44-L49

Is the project you create the changelog for open source? or closed source? 
Is the provided token allowed to access this repo and retrieve its tags  / commit history (in case its closed source?)

**Comment by risoms** [comment]
> Is the project you create the changelog for open source? or closed source? 

Closed source unfortunately.

> Is the provided token allowed to access this repo and retrieve its tags  / commit history (in case its closed source?) 

The token should be able to access the repo. In the proceeding step, I'm able to collect the `from` and `to` using the same token.

**Comment by mikepenz** [comment]
`fromTag` is either resolved via the git repository itself, or provided by the action/ 
`toTag` is resolved relative to the `fromTag` using the git API + semver. 

Currently the action does not use the git API to retrieve the `fromTag`, as this was not the main focus of the action initially. But I see where you are going.

**Comment by mikepenz** [comment]
v2.2.0 will fallback to retrieve the `toTag` from the git API which should significantly improve this situation.
