### ISSUE TITLE
Label extractor method match not working

### ISSUE THREAD

**Issue by dil-kpogany** [mikepenz/release-changelog-builder-action#461]
Hey,

I tried using the new match label extractor method, but for some reason it does not return the desired release note. It might be a misconfiguration on my side. 
I have the following naming convention: [test][ABC-123] - PR title 
Expected output would be to put the PRs under the corresponding title based on the [test] and etc labels, but it puts it all of them under uncategorized. Any idea on what I did wring?

This is the configuration I use:
```
{
    "categories": [
      {
        "title": "## Features",
        "labels": ["[feature]"]
      },
      {
        "title": "## Fixes",
        "labels": ["[fix]"]
      },
      {
        "title": "## Tests",
        "labels": ["[test]"]
      },
      {
        "title": "## Other",
        "labels": []
      }
    ],
    "ignore_labels": [
      "ignore"
    ],
    "sort": "ASC",
    "template": "${{CHANGELOG}}",
    "pr_template": "- ${{TITLE}} @${{AUTHOR}}",
    "empty_template": "- no changes",
    "label_extractor": [
      { 
        "pattern": "\\[feature\\]|\\[test\\]|\\[bug\\]|\\[fix\\]|\\[bugfix\\]|\\[duplicate\\]", 
        "on_property": "title", 
        "method": "match" 
      } 
    ],
  "transformers": [
    {
      "pattern": "[\\-\\*] (\\[(X.+?)\\])(\\[(X.+?)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
      "target": "- $6\n  - FIX https://somelink.net/secure/RapidBoard.jspa?rapidView=783&projectKey=SPE&modal=detail&selectedIssue=$2\n  - FIX https://somelink.net/secure/RapidBoard.jspa?rapidView=783&projectKey=SPE&modal=detail&selectedIssue=$4 | $8"
    },
    {
      "pattern": "[-\\*] (\\[(X.+?)\\])(\\[(.+?)\\])?( )?(.+?)\n(.+?[\\-\\*] )(.+)",
      "target": "- $6\n  - FIX https://somelink.net/secure/RapidBoard.jspa?rapidView=783&projectKey=SPE&modal=detail&selectedIssue=$2 | $8"
    },
    {
      "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
      "target": "- $4\n  - $6"
    }
  ],
    "max_tags_to_fetch": 200,
    "max_pull_requests": 200,
    "max_back_track_time_days": 365,
    "exclude_merge_branches": [
      "Owner/qa"
    ],
    "tag_resolver": {
      "method": "semver"
    },
    "base_branches": [
      "master"
    ]
}
```

Thanks!

**Comment by mikepenz** [comment]
If you want to investigate such cases in detail you can use the test cases and have a test setup with PRs matching your structure:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/__tests__/transform.test.ts#L142-L169

**Comment by mikepenz** [comment]
Generally your configuration looks good, I only believe that you face problems in this case due to case sensitive matching of your Regex. 

If you want to have case insensitive matching use add the `flags: "gui"` to your label extractor. 

------

If you want to investigate such cases in detail you can use the test cases and have a test setup with PRs matching your structure:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/__tests__/transform.test.ts#L142-L169

- download the project
- run `npm install`
- execute the test case: `npm test -- transform.test.ts`

If you use something like `Visual Code` you can even put breakpoints and start a debugging session, can guide you through that if helpful.

**Comment by mikepenz** [comment]
Please let me know if there are more questions, closing for now.
