### ISSUE TITLE
`commitMode` didn't produce output

### ISSUE THREAD

**Issue by itsnotrisky** [mikepenz/release-changelog-builder-action#527]
![Screenshot 2021-10-08 143403](https://user-images.githubusercontent.com/2705042/136494087-1d54f478-9730-4196-b362-b43806181f17.png)

Few things I noticed:
- I have only one input for `commitMode: "true"` yet it says no configuration found.
- On the Load Commit history step it found my 18 commits between last 2 tags, but then it seemed to pass down as pulled requests to the next step. Maybe just some formatting.
- The final output on Create Release results with `- no changes` changelog.

**Comment by mikepenz** [comment]
@itsnotrisky thank you for the ticket. 

The default configuration of the action will have the following default categories: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L49-L62
If no logic is provided on how categories are given to commits they will be moved into the `non categorized` section. 

Due to the main focus of the action on PRs (as those have labels, milestones, ... and much more information available) the log message will state `pull request` while in commit mode these commits are converted so they are handled. 

For commit mode you can provide regex expressions to extract the category from the message fitting your needs:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/configs_test/configuration_commits_emoji.json#L25-L30


Alternative you can configure a configuration to also include `UNCATEGORIZED` results in the report: 
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/configs_test/configuration_commits.json

**Comment by itsnotrisky** [comment]
Thanks for the reply and pointing the config files, I think that's where I missed. I thought by just enabling `commitMode` would dump commit messages but I need to create one category with empty label so that they will come together as uncategorised. Cheers
