### ISSUE TITLE
Add ability to set Regex flags for `transformers`

### ISSUE THREAD

**Issue by MichalWasowskiMeniga** [mikepenz/release-changelog-builder-action#761]
So we have ability to add `flags` property to `duplicate_filter`:
```
"duplicate_filter": {
  "pattern": "\\[ABC-....\\]",
  "on_property": "title",
  "method": "match",
  "flags": "gu" 
}
```
It would be great to have the same ability on `transformers` :)

**Comment by mikepenz** [comment]
So transformers should have the same ability already:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts#L31-L38

When the transformer is constructed we use the flags supplied in the config:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/transform.ts#L396-L399

And these are then used to transform the content:
https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/transform.ts#L76


Sorry for the slow response in looking into it.

**Comment by MichalWasowskiMeniga** [comment]
Hi @mikepenz,

No worries, you've actually been more responsive than I expected 🤣 

That's awesome, so it's only missing from documentation :) 

Tested this and with a transform section like this:
```
"transformers": [
  {
    "pattern": "((?:TEST|ABC))[ -](\\b\\d{3,4}\\b).*",
    "target": "$1-$2 - ",
    "flags": "gui"
  }
]
```
it produced following result:
```
ABC-1234 -
Test-222 -
Test-312 -
TEST-681 -
Update Program.cs
Update Program.cs
```
So all as expected!

ps. I assume the `flags` property is handled per pattern, not global or some overwritten somehow if I would have more entry in `transformers`.

Michal

**Comment by mikepenz** [comment]
😆 yeah, that can vary a lot depending on the time of the year. 

Oh, I see now. Yes that can be, as we moved that flag up at some point. That's why I love to refer to the real `configuration.ts` file with the real definitions: https://github.com/mikepenz/release-changelog-builder-action/blob/develop/src/configuration.ts

Glad it works the way needed for your usecase. 

And yes, the flags are per pattern, so you'll need to provide it for each where you want to differ from the default. 

Have a nice Friday and Weekend :)

**Comment by mikepenz** [comment]
If you have the time, maybe you'd like to open a PR with the addition to the README :)
